--- #YAML:1.0
name:               Xorg-XLFD
version:            0.120
abstract:           
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.1
resources:
    bugtracker:  https://github.com/trapd00r/Xorg-XLFD/issues
    repository:  https://github.com/trapd00r/Xorg-XLFD
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
